name: Bug report
description: Reporta un defecto encontrado
title: "[BUG] <título descriptivo>"
labels: ["bug","triage"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción breve
    validations:
      required: true
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
    validations:
      required: true
  - type: input
    id: esperado
    attributes:
      label: Resultado esperado
    validations:
      required: true
  - type: input
    id: obtenido
    attributes:
      label: Resultado obtenido
    validations:
      required: true
  - type: dropdown
    id: severidad
    attributes:
      label: Severidad
      options: ["Bloqueante","Alta","Media","Baja"]
    validations:
      required: true
  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad
      options: ["P1 - Urgente","P2 - Alta","P3 - Media","P4 - Baja"]
    validations:
      required: true
  - type: input
    id: entorno
    attributes:
      label: Entorno
  - type: textarea
    id: evidencia
    attributes:
      label: Evidencia
