name: Feature request
description: Solicita una mejora o nueva funcionalidad
title: "[FEAT] <título descriptivo>"
labels: ["enhancement"]
body:
  - type: textarea
    id: contexto
    attributes:
      label: Contexto / Problema
    validations:
      required: true
  - type: textarea
    id: propuesta
    attributes:
      label: Propuesta de solución
  - type: textarea
    id: criterios
    attributes:
      label: Criterios de aceptación (Given-When-Then)
